/*

Data Cleaning steps
1. Remove unessary columns by only selecting the ones we need
2. Extract the Tik Tok channel names from the first columns
3. Rename the column names
CREATE VIEW view_us_tiktok_users_2024 AS

*/
CREATE VIEW view_us_tiktok_users_2024 AS
SELECT 
	CAST(SUBSTRING(NAME, 1, CHARINDEX('@', NAME) -1) AS VARCHAR(100)) AS CHANNEL_NAME,
	CASE
        WHEN FOLLOWERS LIKE '%M' THEN CAST(CAST(SUBSTRING(FOLLOWERS, 1, LEN(FOLLOWERS) - 1) AS FLOAT) * 1000000 AS BIGINT)
        WHEN FOLLOWERS LIKE '%B' THEN CAST(CAST(SUBSTRING(FOLLOWERS, 1, LEN(FOLLOWERS) - 1) AS FLOAT) * 1000000000 AS BIGINT)
        ELSE CAST(CAST(FOLLOWERS AS FLOAT) AS BIGINT)
    END AS FOLLOWERS,
    CASE
        WHEN TOTAL_LIKES LIKE '%M' THEN CAST(CAST(SUBSTRING(TOTAL_LIKES, 1, LEN(TOTAL_LIKES) - 1) AS FLOAT) * 1000000 AS BIGINT)
        WHEN TOTAL_LIKES LIKE '%B' THEN CAST(CAST(SUBSTRING(TOTAL_LIKES, 1, LEN(TOTAL_LIKES) - 1) AS FLOAT) * 1000000000 AS BIGINT)
        ELSE CAST(CAST(TOTAL_LIKES AS FLOAT) AS BIGINT)
    END AS TOTAL_LIKES,
    TOTAL_UPLOADS
FROM 
    top_us_tiktok_users_2024;


